name: Run Python Script

on:
  schedule:
    - cron: '30 9 * * *'   # 台灣 17:30（測試）
    - cron: '0 22 * * 0-4' # 台灣 週一～週五 06:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium

      - name: Run script
        run: python MNB.py

      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add news_push_data/

          git diff --cached --quiet || git commit -m "Auto update news data"
          git push
